import { Router } from 'express';
import auth from '../../middlewares/auth';
import { USER_ROLES } from '../../../enums/user';
import { PaymentController } from './payment.controller';
const router = Router();
router.post('/create-checkout-session', auth(USER_ROLES.USER), PaymentController.createCheckoutSession);
router.post('/give-contribution', PaymentController.giveContribution);
router.post('/connect-account', PaymentController.connectAccount);
router.post('/withdraw-funds', PaymentController.withdrawContributionMoney);
export const PaymentRoutes = router;
